### ISSUE TITLE
Unable to fetch IMDB watchlist data.

### ISSUE THREAD

**Issue by iPaulis** [RileyXX/IMDB-Trakt-Syncer#102]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

I just run the script and this is what I get. 
My settings: "sync_watchlist": false, "sync_ratings": true, "remove_watched_from_watchlists": false, "sync_reviews": false

Besides, I don't understand why the script needs to fetch the watchlist, if I've already answered I'm not interested in that.
Anyway, it gives the following error:

PS C:\Users\user> IMDBTraktSyncer
Starting IMDBTraktSyncer....
Your settings are saved at:
C:\Python312\Lib\site-packages\IMDBTraktSyncer
Starting webdriver...

DevTools listening on ws://127.0.0.1:58817/devtools/browser/2245d918-1465-4cd0-96df-e92a8370f2f7
Successfully signed in to IMDB
Processing Trakt Data
Processing Trakt Data Complete
Processing IMDB Data
Unable to fetch IMDB watchlist data.

--- ERROR ---
An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\IMDBTraktSyncer\imdbData.py", line 121, in getImdbData
    raise FileNotFoundError("Watchlist data not found. No CSV files found in the directory")
FileNotFoundError: Watchlist data not found. No CSV files found in the directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\IMDBTraktSyncer\IMDBTraktSyncer.py", line 128, in main
    imdb_watchlist, imdb_ratings, imdb_reviews, errors_found_getting_imdb_reviews = imdbData.getImdbData(imdb_username, imdb_password, driver, directory, wait)
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\IMDBTraktSyncer\imdbData.py", line 163, in getImdbData
    print(f"Error: {error_message}", exc_info=True)
                    ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'error_message' where it is not associated with a value

--------------------------------------------------
Submit the error here: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/new?template=bug_report.yml

### Environment

Win 10
Pip install

**Comment by iPaulis** [comment]
I notice that the imdb export file for my watchlist is created almost instantly on imdb, but my ratings take a while, like a couple of minutes. The script gives me error #101 if I try to manually download and save my ratings in the script folder. However, if I manually save my watchlist csv, even though I'm not interested in it, it does this:

PS C:\Users\user> IMDBTraktSyncer
Starting IMDBTraktSyncer....
Your settings are saved at:
C:\Python312\Lib\site-packages\IMDBTraktSyncer
Starting webdriver...

DevTools listening on ws://127.0.0.1:57426/devtools/browser/15e0ded0-3c25-49ae-8e5c-3819803ebbaa
Successfully signed in to IMDB
Processing Trakt Data
Processing Trakt Data Complete
Processing IMDB Data
Unable to fetch IMDB watchlist data.
Processing IMDB Data Complete
No Trakt Ratings To Set
Setting IMDB Ratings
 - Rating movie: (1 of 18) Whiplash (2014): 9/10 on IMDB
   - Failed to rate movie: (1 of 18) Whiplash (2014): 9/10 on IMDB (tt2582802)
 - Rating movie: (2 of 18) Snatch (2000): 9/10 on IMDB
   - Failed to rate movie: (2 of 18) Snatch (2000): 9/10 on IMDB (tt0208092)
 - Rating movie: (3 of 18) The Departed (2006): 8/10 on IMDB
   - Failed to rate movie: (3 of 18) The Departed (2006): 8/10 on IMDB (tt0407887)
 - Rating movie: (4 of 18) Dune: Part Two (2024): 8/10 on IMDB
   - Failed to rate movie: (4 of 18) Dune: Part Two (2024): 8/10 on IMDB (tt15239678)
 - Rating movie: (5 of 18) Back to the Future (1985): 8/10 on IMDB
   - Failed to rate movie: (5 of 18) Back to the Future (1985): 8/10 on IMDB (tt0088763)
   - Failed to rate movie: (6 of 18) The Green Mile (1999): 8/10 on IMDB (tt0120689)
 - Rating movie: (7 of 18) Parasite (2019): 9/10 on IMDB
   - Failed to rate movie: (7 of 18) Parasite (2019): 9/10 on IMDB (tt6751668)
 - Rating movie: (8 of 18) Gladiator (2000): 8/10 on IMDB
   - Failed to rate movie: (8 of 18) Gladiator (2000): 8/10 on IMDB (tt0172495)
 - Rating movie: (9 of 18) Life Is Beautiful (1997): 10/10 on IMDB
   - Failed to rate movie: (9 of 18) Life Is Beautiful (1997): 10/10 on IMDB (tt0118799)
 - Rating movie: (10 of 18) The Shawshank Redemption (1994): 10/10 on IMDB
   - Failed to rate movie: (10 of 18) The Shawshank Redemption (1994): 10/10 on IMDB (tt0111161)
 - Rating movie: (11 of 18) Top Gun: Maverick (2022): 8/10 on IMDB
   - Failed to rate movie: (11 of 18) Top Gun: Maverick (2022): 8/10 on IMDB (tt1745960)
 - Rating movie: (12 of 18) Arrival (2016): 8/10 on IMDB
   - Failed to rate movie: (12 of 18) Arrival (2016): 8/10 on IMDB (tt2543164)
 - Rating movie: (13 of 18) Interstellar (2014): 9/10 on IMDB
   - Failed to rate movie: (13 of 18) Interstellar (2014): 9/10 on IMDB (tt0816692)
 - Rating movie: (14 of 18) Wonder Woman (2017): 7/10 on IMDB
   - Failed to rate movie: (14 of 18) Wonder Woman (2017): 7/10 on IMDB (tt0451279)
 - Rating movie: (15 of 18) The Avengers (2012): 8/10 on IMDB
   - Failed to rate movie: (15 of 18) The Avengers (2012): 8/10 on IMDB (tt0848228)
 - Rating movie: (16 of 18) Doctor Strange (2016): 7/10 on IMDB
   - Failed to rate movie: (16 of 18) Doctor Strange (2016): 7/10 on IMDB (tt1211837)
 - Rating movie: (17 of 18) The Matrix (1999): 9/10 on IMDB
   - Failed to rate movie: (17 of 18) The Matrix (1999): 9/10 on IMDB (tt0133093)
 - Rating movie: (18 of 18) Suicide Squad (2016): 5/10 on IMDB
   - Failed to rate movie: (18 of 18) Suicide Squad (2016): 5/10 on IMDB (tt1386697)
Setting IMDB Ratings Complete
No Trakt Reviews To Set
No IMDB Reviews To Set
No Watched Items To Remove From Trakt Watchlist
No Watched Items To Remove From IMDB Watchlist
Closing webdriver...
IMDBTraktSyncer Complete

So I guess it does not manage to download my ratings csv and says there is nothing to sync into trakt, which is not true, there are almost 2000 titles to sync. Then it tries to sync from trakt into imdb, which also fails.

**Comment by iPaulis** [comment]
OK, everything seems to be a language issue. My system language is Spanish, so my chrome loads the pages in spanish by default and the script was trying to find certain texts in english to navigate through the buttons and such, and it would have never worked.
I partially fixed it in the code like in the line 54 in imdbData.py and some other instances:
`if "in progress" in item.text.lower() or "en curso" in item.text.lower():`

But eventually I realized it would not be enough with a few fixes for spanish, because even the imdb export csv files are also in spanish, with the "Title type" column with values in spanish, and so on.

In the end I switched the chrome page into english, re-run everything with new exports and it fixed all the issues. Now everything seems to work fine.
You might want to consider adding a warning about setting imdb in english as a requirement, or ideally test if you can force webdriver chrome or whatever part working in the background to load the page always in english, regardless of the system language.

**Comment by RileyXX** [comment]
Thank you very much for reporting this. I see the issue you're having. 

In a recent release the IMDB csv data structure changed and went unnoticed until a user noticed and reported it. A fix was implemented and part of the fix was some checks to try and prevent this from happening again in the future. This fix had to do with checking the colum names specifically to verify the correct format however alternate languages weren't taken into consideration. I'll look into this soon and figure out the best possible solution.
