### ISSUE TITLE
Error retrieving latest version: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)> Could not retrieve the latest version.

### ISSUE THREAD

**Issue by CabbageMcHead** [RileyXX/IMDB-Trakt-Syncer#105]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Error retrieving latest version: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
Could not retrieve the latest version.
No matching chromedriver-py version found for Chrome 	<string>128
Your settings are saved at:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer

Please visit the following URL to authorize this application: 
https://trakt.tv/oauth/authorize?response_type=code&client_id=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz&redirect_uri=urn:ietf:wg:oauth:2.0:oob

Please enter the authorization code from the URL: zzzzzzzzz
   - Request failed with exception: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/IMDBtraktsyncer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 20, in main
    from IMDBTraktSyncer import verifyCredentials as VC
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer/verifyCredentials.py", line 335, in <module>
    trakt_client_id, trakt_client_secret, trakt_access_token, trakt_refresh_token, imdb_username, imdb_password = prompt_get_credentials()
                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer/verifyCredentials.py", line 82, in prompt_get_credentials
    trakt_access_token, trakt_refresh_token = authTrakt.authenticate(client_id, client_secret)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

### Environment

MacOS 14.6.1

**Comment by RileyXX** [comment]
Are you still having this issue? Looks like an issue with the Trakt API url SSL certificate. The API might have been down temporarily. If you're still having this issue let me know. 

One thing you can try is deleting the credentials.txt file in your install path to reset the script in case it was corrupted somehow (you will need to re-enter you credentials).
