### ISSUE TITLE
'time' not defined, issue with v1.3.1 after upgrade from v1.2.0

### ISSUE THREAD

**Issue by CabbageMcHead** [RileyXX/IMDB-Trakt-Syncer#37]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 180, in main
    response = EH.make_trakt_request(url, payload=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer/errorHandling.py", line 49, in make_trakt_request
    time.sleep(retry_delay)
    ^^^^
NameError: name 'time' is not defined

### Environment

MacOS Ventura 13.4
Python 3.11

**Comment by RileyXX** [comment]
Hi, thanks for opening an issue! It looks like an import was unintentionally removed in one of the recent patches. This should be fixed now in v1.3.2. Let me know if this fixes it for you. 

For pip install you can update to the latest version using the following:
````
python -m pip install IMDBTraktSyncer --upgrade
````
Alternatively, you can download the latest .zip from the [releases page](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases).

**Comment by CabbageMcHead** [comment]
Perfect - it's working fine again!

Thanks for putting together these really useful scripts!

**Comment by RileyXX** [comment]
> Perfect - it's working fine again! Thanks for putting together these really useful scripts!

No problem, glad it's working now! These scripts are very useful indeed. If you have any other issues feel free to open another bug report.
