### ISSUE TITLE
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (923, 673)

### ISSUE THREAD

**Issue by CabbageMcHead** [RileyXX/IMDB-Trakt-Syncer#42]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 211, in main
    watchlist_button.click()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (923, 673)
  (Session info: chrome=113.0.5672.126)
Stacktrace:
0   chromedriver_mac_arm64              0x0000000100b182b8 chromedriver_mac_arm64 + 4260536
1   chromedriver_mac_arm64              0x0000000100b1094c chromedriver_mac_arm64 + 4229452
2   chromedriver_mac_arm64              0x000000010074c9d4 chromedriver_mac_arm64 + 281044
3   chromedriver_mac_arm64              0x000000010078e134 chromedriver_mac_arm64 + 549172
4   chromedriver_mac_arm64              0x000000010078c094 chromedriver_mac_arm64 + 540820
5   chromedriver_mac_arm64              0x0000000100789fac chromedriver_mac_arm64 + 532396
6   chromedriver_mac_arm64              0x000000010078937c chromedriver_mac_arm64 + 529276
7   chromedriver_mac_arm64              0x000000010077d984 chromedriver_mac_arm64 + 481668
8   chromedriver_mac_arm64              0x000000010077d1cc chromedriver_mac_arm64 + 479692
9   chromedriver_mac_arm64              0x00000001007be7e4 chromedriver_mac_arm64 + 747492
10  chromedriver_mac_arm64              0x000000010077b98c chromedriver_mac_arm64 + 473484
11  chromedriver_mac_arm64              0x000000010077c98c chromedriver_mac_arm64 + 477580
12  chromedriver_mac_arm64              0x0000000100ad6a6c chromedriver_mac_arm64 + 3992172
13  chromedriver_mac_arm64              0x0000000100adacd0 chromedriver_mac_arm64 + 4009168
14  chromedriver_mac_arm64              0x0000000100ae0d48 chromedriver_mac_arm64 + 4033864
15  chromedriver_mac_arm64              0x0000000100adb940 chromedriver_mac_arm64 + 4012352
16  chromedriver_mac_arm64              0x0000000100ab357c chromedriver_mac_arm64 + 3847548
17  chromedriver_mac_arm64              0x0000000100af9400 chromedriver_mac_arm64 + 4133888
18  chromedriver_mac_arm64              0x0000000100af9558 chromedriver_mac_arm64 + 4134232
19  chromedriver_mac_arm64              0x0000000100b09c3c chromedriver_mac_arm64 + 4201532
20  libsystem_pthread.dylib             0x000000019307ffa8 _pthread_start + 148
21  libsystem_pthread.dylib             0x000000019307ada0 thread_start + 8

### Environment

MacOS Ventura 13.4
Python 3.11

**Comment by RileyXX** [comment]
Hi, thanks for the detailed error log! I have implemented some changes in the latest release ([v1.3.7](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v1.3.7)) which should fix this error. If could please update to the latest version and confirm whether or not you are still getting this error that would be helpful. If you have any other issues errors messages let me know and I will take a look. Thanks!

For pip install you can update to the latest version using the following:
````
python -m pip install IMDBTraktSyncer --upgrade
````
Alternatively, you can download the latest .zip from the [releases page](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases).

**Comment by RileyXX** [comment]
> It's working perfectly! Thanks for solving this issue quickly and congrats again on the very useful scripts.

Thanks for confirming! Feel free to open another bug report if you have any other issues.
