### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by shadjisolomou** [RileyXX/IMDB-Trakt-Syncer#86]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\site-packages\IMDBTraktSyncer\IMDBTraktSyncer.py", line 123, in main
    trakt_watchlist, trakt_ratings, trakt_reviews, watched_content = traktData.getTraktData()
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\site-packages\IMDBTraktSyncer\traktData.py", line 18, in getTraktData
    json_data = json.loads(response.text)
                           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

### Environment

OS: Win10, Uses pip install:yes

**Comment by RileyXX** [comment]
Are you still having this issue? See if you can get more of the error message there might be some details missing here. 

This is kind of a generic error that can happen if the Trakt API is down or if your credentials (api keys etc) are incorrect.

**Comment by RileyXX** [comment]
This bug should be fixed in the latest version v1.9.5. If you're still having problems with this let me know and I can reopen this issue. Thanks
